#define ORGAN_SLOT_PENIS "penis"
#define ORGAN_SLOT_TESTICLES "testicles"
#define ORGAN_SLOT_BREASTS "breasts"
#define ORGAN_SLOT_VAGINA "vagina"

#define BODYPART_FEATURE_CHASTITY "chastity"
#define BODYPART_FEATURE_PUBES "pubes"
#define BODYPART_FEATURE_PITS "pits"

#define BODY_HAIR_MATERIAL_HAIR 1
#define BODY_HAIR_MATERIAL_FUR 2
#define BODY_HAIR_MATERIAL_FEATHERS 3
#define BODY_HAIR_MATERIAL_FUZZ 4
#define BODY_HAIR_MATERIAL_BRAIDS 5
