/datum/faith/old_god
	name = "Genesism"
	desc = "	</br>''When all yet began, there was but ONE. When all yet passes, there shall only be ONE.'' </br>	\
	</br>After the impossible break of the Shattering, GOD - named PSYDON - broke asunder- and shattered the World with it. Most had feared that He had undertaken the ultimate sacrifice to save this world from the Anathema's assault, and - in the midst of mourning - turned their prayers to Lesser Divines to end the Anatheme's atrocity. Here in the Now, however, worship of the Living Gods continue- even if they are sired from HIM, and borne from his Fragments. Yet, throughout the ages, there always remained those who kept faith in Psydon above all else: be it in one way, or another. </br>	\
	</br>Amongst the countless denominations that're peppered across the world, and the three major prongs of the Faith, the Orthodoxy is the most widely-practiced: preached by the fellow theocracies of venerable Naledi and Otava. </br>	\
	</br>The Orthodoxists believe that Psydon still lives, and is soon destined to return. Unanswered prayers and faltering miracles are merely tests of faith, nothing more. While the Pantheon's Fragments and other Living Gods might be venerable, they are still His children: and as such, they remain wholly subservient to His divine authority. Those of the Ascendant defy this divine order, however, and must be put to Cross - or Death. </br>	\
	</br> With the passage of time - and in the breadth of belief - the Psydonian faith has expanded across the world; to the point where many of the converted have come to blows with their Pantheonic host. Outwardly, the Orthodoxy preaches pacifism, charity, and persistence in the face of every adversity. The Pantheon and Temple are allies, they preach- together, the Fragments can be unified, and all Wounds healed. </br>	\
	</br> Yet still- the bloody branches of His Majesty's Holy Inquisition suffuse almost every kingdom in the Midderland - and few do not recognize their state-embraced cruelties, nor how spiritual awakenings and Psydonian insurrection tend to rise in their presence. All recognize, now, the fanaticism, the veneration, the the duty and violence behind this single mantra - ENDURE. </br>"
	worshippers = "Traditionalists, Spiritualists, Accelerationists, Anti-Slavers, and the Hopeful "
	godhead = /datum/patron/old_god
